### ISSUE TITLE
Unable to record. There is no video file in the directory

### ISSUE THREAD

**Issue by xunzh2000** [terrorist-squad/DockerChaturbateRecorderGUI#27]
Unable to record. There is no video file in the directory. Added channel to show all offline。The environment is VMware virtual CentOS 8. After installing the pagoda, docker is installed, and the image is pulled. The settings and log are as follows：

![QQ图片20220728084834](https://user-images.githubusercontent.com/48504897/181396882-70bdcfab-62ce-49b4-ab10-86c3bcb69a74.png)
![QQ截图20220728085133](https://user-images.githubusercontent.com/48504897/181397187-cda9e3c5-d1ca-438c-bf04-c5ef61a79316.png)

usermod: UID '0' already exists
groupmod: invalid group ID 'recorder'
-> lösche Cache
-> Migrate
[36;1mMigrations for 'main':[0m
![QQ图片20220728084834](https://user-images.githubusercontent.com/48504897/181396882-70bdcfab-62ce-49b4-ab10-86c3bcb69a74.png)

  [1mapps/frontend/main/migrations/0001_initial.py[0m
    - Create model WishlistItem
[36;1mOperations to perform:[0m
[1m  Apply all migrations: [0madmin, auth, contenttypes, main, sessions
[36;1mRunning migrations:[0m
  No migrations to apply.
-> compilemessages
-> starte server 
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
July 28, 2022 - 00:42:37
Django version 4.0.1, using settings 'config.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[28/Jul/2022 00:42:37] [m"GET /wishlist/ HTTP/1.1" 200 1657[0m
[28/Jul/2022 00:42:42] [m"GET /wishlist/ HTTP/1.1" 200 1657[0m
[28/Jul/2022 00:42:47] [m"GET /wishlist/ HTTP/1.1" 200 1657[0m
[28/Jul/2022 00:42:52] [m"GET /wishlist/ HTTP/1.1" 200 1657[0m
[28/Jul/2022 00:42:57] [m"GET /wishlist/ HTTP/1.1" 200 1657[0m
Traceback (most recent call last):
  File "/code/manage.py", line 22, in 
    main()
  File "/code/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/code/utils/management/commands/check_chatrubate.py", line 195, in handle
    self.checkChannels()
  File "/code/utils/management/commands/check_chatrubate.py", line 75, in checkChannels
    containers = self.getInstances()
  File "/code/utils/management/commands/check_chatrubate.py", line 62, in getInstances
    command = self.adapter_factory.create_adapter(os.environ['COMMAND_ADAPTER']).getInstances(self.containerPrefix)
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'COMMAND_ADAPTER'
[28/Jul/2022 00:43:02] [m"GET /wishlist/ HTTP/1.1" 200 1657[0m
[28/Jul/2022 00:43:07] [m"GET /wishlist/ HTTP/1.1" 200 1657[0m

Please guide me where the problem is? thank you

**Comment by terrorist-squad** [comment]
If you have docker installed, then you can use this command to start it:
docker run -it --rm -v /Users/christianknedel/videos:/code/database -v /var/run/docker.sock:/var/run/docker.sock -p 8002:8000 -e TZ="Europe/Berlin" -e ABSOLUTE_HOST_MEDIA="/Users/christianknedel/videos/" -e COMMAND_ADAPTER='DockerAdapter' -e CONTAINER_PREFFIX='cr_' -e RECORDER_IMAGE='chrisknedel/chatrubate-recorder:3.0' chrisknedel/chatrubate-recorder-gui:3.0


please try it without pagoda

Translated with www.DeepL.com/Translator (free version)

**Comment by terrorist-squad** [comment]
If you have docker installed, then you can use this command to start it:
docker run -d --rm -v /Users/christianknedel/videos:/code/database -v /var/run/docker.sock:/var/run/docker.sock -p 8002:8000 -e TZ="Europe/Berlin" -e ABSOLUTE_HOST_MEDIA="/Users/christianknedel/videos/" -e COMMAND_ADAPTER='DockerAdapter' -e CONTAINER_PREFFIX='cr_' -e RECORDER_IMAGE='chrisknedel/chatrubate-recorder:3.0' chrisknedel/chatrubate-recorder-gui:3.0

please try it without pagoda
